apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: preprod-

images:
  - name: bob2606/hello-http
    newtag: 0.8.33

replicas:
  - name: hello
    count: 2

configMapGenerator:
  - name: hello-env
    envs:
      - hello.env
