apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: prod
namePrefix: prod-

images:
  - name: bob2606/hello-http
    newtag: 0.8.32

replicas:
  - name: hello
    count: 5

configMapGenerator:
  - name: hello-env
    envs:
      - hello.env
